### ISSUE TITLE
Large integer `image tag` gets converted to scientific notation

### ISSUE THREAD

**Issue by Kiougar** [bookingcom/shipper#102]
When an `image tag` is a large integer (e.g. `20190612073634`) it gets converted to the scientific notation (e.g `2.0190612073634e+13`)

For example the following `release` configuration:
```yaml
Values:
  Image:
    Repository:  [...]
    Tag:         20190612073634
```

Results in this `pod` configuration:
```yaml
Containers:
  app:
    Container ID:
    Image:          [...]:2.0190612073634e+13
```

As a result, the pod is at `InvalidImageName` error state
