### ISSUE TITLE
Improve Reporting In the Release Object About the Fleet

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#139]
Now that we have the fleet summary report in the CapacityTarget object, we can summarise it in a way that is easy to read in the conditions of the Release object.

We need to figure out the answers to the following questions:

- How can we use the fleet summary to figure out what's wrong?
- Once we figure it out, how can we turn it into a string short enough to be put into the `message` of a condition?

**Comment by icanhazbroccoli** [comment]
An example of the output I've came up so far:
Happy state:
```
  reports:
  - achievedPercent: 100
    availableReplicas: 2
    cluster: docker-desktop
    summary: |-
      2 container(s) [nginx(x2)] are in status: ContainersReady:True
      2 container(s) [nginx(x2)] are in status: Initialized:True
      2 container(s) [nginx(x2)] are in status: PodScheduled:True
      2 container(s) [nginx(x2)] are in status: Ready:True
```
Unhappy state:
```
  reports:
  - cluster: docker-desktop
    problems: 'PodScheduled:False, reason: Unschedulable, message: 0/1 nodes are available:
      1 Insufficient cpu, 1 Insufficient memory.'
```
