### ISSUE TITLE
question about release and moving from helm to kustomize

### ISSUE THREAD

**Issue by Colstuwjx** [bookingcom/shipper#142]
Hi team,

I have some questions about shipper release design, and the changes by moving from helm to kustomize.

Q1: how shipper do release in kubernetes? As we are using helm to manage application configuration, does shipper do release by `helm install`? How shipper check that the new release is ready?

Q2: I have seen your RFC about moving from helm to kustomize, and the question is, if we moved to kustomize, by using kustomize to instantiate application.yaml like the [PR said](https://github.com/bookingcom/shipper/pull/101/files#diff-e56ce054108cb24df6c9a35cb61b16beR60):

```
---
apiVersion: shipper.booking.com/v1alpha1
kind: Application
metadata:
  name: bikerental
spec:
  template:
    clusterRequirements:
      regions:
      - name: eu-nl
      capabilities: []
    kustomization:
      bases:
        - https://example.com/core # <1>
      namePrefix: bikerental-
      commonLabels:
        app: bikerental
      patchesStrategicMergeInline: # <2>
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: app
          spec:
            containers:
              name: app
              env:
                - name: BIKE_COLORS
                  value: red,green,blue
      patchesStrategicMerge:
        - https://example.com/sidecars/sidecar.yaml # <1>
      images:
        - name: app
          newName: juliogreff/bikerental
          newTag: deadcafe
    strategy:
      steps:
      - name: full on
        capacity:
          incumbent: 0
          contender: 100
        traffic:
          incumbent: 0
          contender: 100
```

we don't event know what's the final k8s object manifest about the application, in other words, we don't have the whole picture for the app running inside k8s! If it says kustomize is the `make` in cloud native, we finally need to build the `bundle` by `make`, rather than always do `make` for releasing.

Just some questions about shipper, BTW, shipper is awesome, I'm totally agree the requirements of rollout strategy and app configuration management!

Thanks.
