### ISSUE TITLE
Create a `Ready` condition in TrafficTarget to inform Release Controller when traffic has been achieved

### ISSUE THREAD

**Issue by isutton** [bookingcom/shipper#24]
## Motivation

The current implementation of the Strategy Controller can't reliably determine, with the information currently available, whether a traffic shifting operation is finished without consider the implementation details of the traffic shifting backend.

In order to make this decision process more precise and reliable, we need to either:

1. Add more information regarding the internals of the current traffic shifting backend implementation, encoded in the Traffic Target object (for example, number of replicas for the pod labeling traffic shifting implementation for a particular cluster); or
2. Adjust the Traffic Target object interface to encode in `.status` the the last desired weight, the achieved weight **and** whether, from the Traffic Controller perspective, the optimal weight for the given desired weight has been achieved. 

Between those two approaches, I chose to describe, in this document, the implementation of 2. because:

- Makes the Strategy Controller less aware of any  Traffic Controller traffic shifting internal implementation details, thus making its decision process simpler;
- Makes the Traffic Controller very independent, meaning the traffic shifting implementation can be swapped and no other changes in the system would be required;
- Doesn't require any design regarding generic primitives to allow swapping traffic shifting implementations.

## Changes

Both Traffic Controller and Strategy Controller should be modified to encode this information in each cluster traffic status' conditions, and use this information to decide whether to continue the strategy, respectively.

In the current implementation, the Traffic Controller uses the information encoded in `.spec.clusters[].weight` as input to the new state it should try to converge. Once it has finished its work (regardless of internal implementation) it encodes the results in `.status.clusters[].achievedTraffic`, leaving the interpretation of whether the achieved traffic is appropriate to continue the strategy or not to the Strategy Controller.

The current traffic shifting implementation (adding Pods to a specific Service through labels) falls short in situations where the specified weight can never be achieved; for example, any weight that would represent 50% of traffic of a deployment with 3 replicas. 

This requires the Strategy Controller to consider whether a Release is the contender or incumbent to properly evaluate whether the desired state has been achieved, requiring the Strategy Controller to know more about the traffic shifting implementation than it should.

One option to alleviate this issue is to encode whether the optimal weight has been achieved from the point of view of the Traffic Controller through the `Ready` condition in `.status.clusters[].conditions`.

Take in account the following Traffic Target object excerpt:

```yaml
spec:
  clusters:
  - name: cluster-a
    weight: 50
```

We have an internal policy to always round up any calculations involving number of replicas, both for capacity and the current traffic shifting implementation. This means that when the strategy requires the equivalent of 50% of 3 replicas, 2 replicas will be included in the load balancer.

Considering that the Release associated with this object has specified 3 replicas, its `.status` field might end up like the following:

```yaml
status:
  clusters:
  - name: cluster-a
    achievedTraffic: 67
```

With this information at hand, the Strategy Controller can't actually decide whether or not the Traffic Controller can still converge into the desired weight. At least not without understanding the current traffic shifting implementation, as previously stated.

To solve this issue, the Traffic Controller should then encode whether it can still converge (or not) into the desired weight through the `Ready` conditions, like the following:

```yaml
status:
  clusters:
  - name: cluster-a
    achievedTraffic: 67
    conditions:
    - type: Ready
      status: False
      reason: EndpointMissingReplicas
      message: The Endpoint associated to this Release's Service doesn't include the number of replicas expected (1 out of 2)
```

Once the Traffic Controller identifies that all the work required to fulfill to achieve the desired state, this information should be encoded in the same `Ready` condition, like the following:

```yaml
status:
  clusters:
  - name: cluster-a
    achievedTraffic: 67
    conditions:
    - type: Ready
      status: True
      reason: EndpointHasAllDesiredReplicas
      message: The Endpoint associated to this Release's Service include all replicas expected (2 out of 2)
```

Unfortunately this isn't enough for the Strategy Controller to perform its work; in a very probably case where the Strategy Controller modifies `.spec.clusters[].weight` and the Traffic Controller hasn't picked that up to work (for example, Shipper is busy) the Strategy Controller might wrongly infer, by looking solely at the `Ready` condition that the strategy step status has been achieved. To avoid this scenario, we need to include the desired weight in `.status.clusters[]` as well. This state would look like the following:

```yaml
spec:
  clusters:
  - name: cluster-a
    weight: 60
status:
  clusters:
  - name: cluster-a
    desiredWeight: 50
    achievedTraffic: 67
    conditions:
    - type: Ready
      status: True
      reason: EndpointHasAllDesiredReplicas
      message: The Endpoint associated to this Release's Service include all replicas expected (2 out of 2)
```

The Strategy Controller should then, when evaluating whether or not continue the strategy, check whether `.spec.clusters[].weight` matches `.status.clusters[].desiredWeight` and only then check whether the `Ready` condition is `True`. This means that in the previous listing the Strategy Controller **would not** continue the strategy until the Traffic Controller does its job. The following listing shows the Traffic Target object after it's been touched by the Traffic Controller:

```yaml
spec:
  clusters:
  - name: cluster-a
    weight: 60
status:
  clusters:
  - name: cluster-a
    desiredWeight: 60
    achievedTraffic: 67
    conditions:
    - type: Ready
      status: True
      reason: EndpointHasAllDesiredReplicas
      message: The Endpoint associated to this Release's Service include all replicas expected (2 out of 2)
```

The Strategy Controller would evaluate, for this particular state, that the strategy step has been finished and can move to the next action.

In the case of multiple clusters, the Strategy Controller would consider that a step has been finished when all clusters listed in `.spec.clusters[]` have the same weight in `.status.clusters[]`, and all clusters' `Ready` condition have `True` status.
