### ISSUE TITLE
YAML problems on the Application object are not surfaced

### ISSUE THREAD

**Issue by kanatohodets** [bookingcom/shipper#51]
Today a user inserted the following Application object into a management cluster:

```yaml
apiVersion: shipper.booking.com/v1alpha1                                                                                                                                                                                                                                                                                                                                                               
kind: Application                                                                                                                                                                                                                                                                                                                                                                                
metadata:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  name: some-application                                                                                                                                                                                                                                                                                                                                                                                 
  namespace: some-namespace                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
spec:                                                                                                                                                                                                                                                                                                                                                                                            
  revisionHistoryLimit: 10                                                                                                                                                                                                                                                                                                                                                                       
  template:                                                                                                                                                                                                                                                                                                                                                                                      
    chart:                                                                                                                                                                                                                                                                                                                                                                                       
      name: cool-chart                                                                                                                                                                                                                                                                                                                                                                                 
      repoUrl: https://internal-chart-repo.example.com/charts                                                                                                                                                                                                                                                                                                                                            
      version: 12                                                                                                                                                                                                                                                                                                                                                                            
    clusterRequirements:                                                                                                                                                                                                                                                                                                                                                                         
      capabilities:                                                                                                                                                                                                                                                                                                                                                                              
      - cloudlb                                                                                                                                                                                                                                                                                                                                                                                      
      regions:                                                                                                                                                                                                                                                                                                                                                                                   
      - name: us-east1                                                                                                                                                                                                                                                                                                                                                                             
        replicas: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    sidecars:
      foo:
        enabled: false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    strategy:                                                                                                                                                                                                                                                                                                                                                                                    
      steps:                                                                                                                                                                                                                                                                                                                                                                                     
      - capacity:                                                                                                                                                                                                                                                                                                                                                                                
          contender: 1                                                                                                                                                                                                                                                                                                                                                                           
          incumbent: 100                                                                                                                                                                                                                                                                                                                                                                         
        name: staging                                                                                                                                                                                                                                                                                                                                                                            
        traffic:                                                                                                                                                                                                                                                                                                                                                                                 
          contender: 0                                                                                                                                                                                                                                                                                                                                                                           
          incumbent: 100                                                                                                                                                                                                                                                                                                                                                                         
      - capacity:                                                                                                                                                                                                                                                                                                                                                                                
          contender: 10                                                                                                                                                                                                                                                                                                                                                                          
          incumbent: 90                                                                                                                                                                                                                                                                                                                                                                          
        name: canary                                                                                                                                                                                                                                                                                                                                                                           
        traffic:                                                                                                                                                                                                                                                                                                                                                                                 
          contender: 10                                                                                                                                                                                                                                                                                                                                                                          
          incumbent: 90                                                                                                                                                                                                                                                                                                                                                                          
      - capacity:                                                                                                                                                                                                                                                                                                                                                                                
          contender: 100                                                                                                                                                                                                                                                                                                                                                                         
          incumbent: 0                                                                                                                                                                                                                                                                                                                                                                           
        name: full on                                                                                                                                                                                                                                                                                                                                                                            
        traffic:                                                                                                                                                                                                                                                                                                                                                                                 
          contender: 100                                                                                                                                                                                                                                                                                                                                                                         
          incumbent: 0                                                                                                                                                                                                                                                                                                                                                                           
    values:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      image:                                                                                                                                                                                                                                                                                                                                                                                     
        repository: internal-docker-registry.example.com                                                                                                                                                                                                                                                                                                                       
        tag: deadbeef                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
      ports:                                                                                                                                                                                                                                                                                                                                                                                     
      - 443                                                                                                                                                                                                                                                                                                                                                                                      
      replicaCount: 1        
```

This yielded errors in the Shipper logs like so:

```
E1122 14:54:29.831311       1 reflector.go:205] github.com/bookingcom/shipper/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Application: v1alpha1.ApplicationList: Items: []v1alpha1.Application: v1alpha1.Application: Spec: v1alpha1.ApplicationSpec: Template: v1alpha1.ReleaseEnvironment: Sidecars: []v1alpha1.Sidecar: ReadArrayCB: expect [ or n, but found {, error found in #10 byte of ...|idecars":{"foo":|..., bigger context ... ,"sidecars":{"foo":{"enabled":false}},"strategy":{"steps":[|...
```
(there's an error in the Application yaml: 'sidecars' is a vestigial key that we should delete, and it had contents that our struct doesn't expect)

The Application object had no 'status' written, no events, and no Release created. As a result, the user was really confused about why their rollout wasn't going anywhere.

A few tasks here:

1) remove 'sidecars' from our Application/Release API, Shipper isn't doing sidecar injection and probably shouldn't start without careful consideration.
2) Make sure that YAML problems in the `template` are surfaced in 'status' and events of the Application, ideally also on a Release object.
3) Look into stricter validation using an admission controller or similar.
